Organizations:
  - &OrdererOrg
    Name: Orderer
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/delivery-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"

  - &restaurant
    Name: restaurantMSP
    ID: restaurantMSP
    MSPDir: crypto-config/peerOrganizations/restaurant.delivery-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('restaurantMSP.admin', 'restaurantMSP.peer', 'restaurantMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('restaurantMSP.admin', 'restaurantMSP.peer', 'restaurantMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('restaurantMSP.admin', 'restaurantMSP.peer', 'restaurantMSP.client')"
    AnchorPeers:
      - Host: peer0.restaurant.delivery-network.com
        Port: 11051

  - &squad
    Name: squadMSP
    ID: squadMSP
    MSPDir: crypto-config/peerOrganizations/squad.delivery-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('squadMSP.admin', 'squadMSP.peer', 'squadMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('squadMSP.admin', 'squadMSP.peer', 'squadMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('squadMSP.admin', 'squadMSP.peer', 'squadMSP.client')"
    AnchorPeers:
      - Host: peer0.squad.delivery-network.com
        Port: 13051

  - &customer
    Name: customerMSP
    ID: customerMSP
    MSPDir: crypto-config/peerOrganizations/customer.delivery-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('customerMSP.admin', 'customerMSP.peer', 'customerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('customerMSP.admin', 'customerMSP.peer', 'customerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('customerMSP.admin', 'customerMSP.peer', 'customerMSP.client')"
    AnchorPeers:
      - Host: peer0.customer.delivery-network.com
        Port: 7051


#Capabilities

Capabilities:
  Channel: &ChannelCapabilities
    V1_4_3: true
    V1_3: false
    V1_1: false
  Orderer: &OrdererCapabilities
    V1_4_2: true
    V1_1: false
  Application: &ApplicationCapabilities
    V1_4_2: true
    V1_3: false
    V1_2: false
    V1_1: false

#Application

Application: &ApplicationDefaults
  Organizations:
  Policies: &ApplicationDefaultPolicies
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities: *ApplicationCapabilities

#Orderer
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.delivery-network.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Capabilities: *OrdererCapabilities
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    # BlockValidation specifies what signatures must be included in the block
    # from the orderer for the peer to validate it.
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    # Who may invoke the 'Deliver' API
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    # Who may invoke the 'Broadcast' API
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    # By default, who may modify elements at this config level
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities


#Profiles
Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      DeliveryConsortium:
        Organizations:
          - *restaurant
          - *squad
          - *customer

  DeliveryChannel:
    Consortium: DeliveryConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *restaurant
        - *squad
        - *customer
      Capabilities:
        <<: *ApplicationCapabilities
