version: "2"

volumes:
  orderer.delivery-network.com:
  peer0.customer.delivery-network.com:
  peer1.customer.delivery-network.com:
  peer0.squad.delivery-network.com:
  peer1.squad.delivery-network.com:
  peer0.restaurant.delivery-network.com:
  peer1.restaurant.delivery-network.com:
  
networks:
  delivery-network:

services:
  ca.customer.delivery-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.customer.delivery-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.registrar.property-registration-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/754fccf4ad3f6a483161cf597b79fbdbdadaf1ee2f024e79da8c8e9b8bfb6dcb_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.registrar.property-registration-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/754fccf4ad3f6a483161cf597b79fbdbdadaf1ee2f024e79da8c8e9b8bfb6dcb_sk
    volumes:
      - ./crypto-config/peerOrganizations/customer.delivery-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.customer.delivery-network.com
    networks:
      - delivery-network

  ca.squad.delivery-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.squad.delivery-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    volumes:
      - ./crypto-config/peerOrganizations/squad.delivery-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.squad.delivery-network.com
    networks:
      - delivery-network

  ca.restaurant.delivery-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.restaurant.delivery-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.users.property-registration-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    volumes:
      - ./crypto-config/peerOrganizations/restaurant.delivery-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.restaurant.delivery-network.com
    networks:
      - delivery-network

  orderer.delivery-network.com:
    extends:
      file: docker-base/docker-compose-base.yaml
      service: orderer.delivery-network.com
    container_name: orderer.delivery-network.com
    networks:
      - delivery-network

  peer0.customer.delivery-network.com:
    container_name: peer0.customer.delivery-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.customer.delivery-network.com
    networks:
      - delivery-network

  peer1.customer.delivery-network.com:
    container_name: peer1.customer.delivery-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.customer.delivery-network.com
    networks:
      - delivery-network

  peer0.squad.delivery-network.com:
    container_name: peer0.squad.delivery-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.squad.delivery-network.com
    networks:
      - delivery-network

  peer1.squad.delivery-network.com:
    container_name: peer1.squad.delivery-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.squad.delivery-network.com
    networks:
      - delivery-network

  peer0.restaurant.delivery-network.com:
    container_name: peer0.restaurant.delivery-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.restaurant.delivery-network.com
    networks:
      - delivery-network

  peer1.restaurant.delivery-network.com:
    container_name: peer1.restaurant.delivery-network.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.restaurant.delivery-network.com
    networks:
      - delivery-network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.restaurant.delivery-network.com:7051
      - CORE_PEER_LOCALMSPID=restaurantMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/restaurant.delivery-network.com/peers/peer0.restaurant.delivery-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/restaurant.delivery-network.com/peers/peer0.restaurant.delivery-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/restaurant.delivery-network.com/peers/peer0.restaurant.delivery-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/restaurant.delivery-network.com/users/Admin@restaurant.delivery-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
      - ./../chaincode-advanced/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode-advanced/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.customer.delivery-network.com
      - ca.squad.delivery-network.com
      - ca.restaurant.delivery-network.com
      - orderer.delivery-network.com
      - peer0.customer.delivery-network.com
      - peer1.customer.delivery-network.com
      - peer0.squad.delivery-network.com
      - peer1.squad.delivery-network.com
      - peer0.restaurant.delivery-network.com
      - peer1.restaurant.delivery-network.com

    networks:
      - delivery-network

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv:latest
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=peer0.restaurant.delivery-network.com:7051
      - CORE_PEER_LOCALMSPID=restaurantMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/restaurant.delivery-network.com/users/Admin@restaurant.delivery-network.com/msp
      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/crypto/peerOrganizations/restaurant.delivery-network.com/users/Admin@restaurant.delivery-network.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/crypto/peerOrganizations/restaurant.delivery-network.com/users/Admin@restaurant.delivery-network.com/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/crypto/peerOrganizations/restaurant.delivery-network.com/users/Admin@restaurant.delivery-network.com/tls/ca.crt
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode:/opt/gopath/src/chaincode
      - ./../chaincode-advanced:/opt/gopath/src/chaincode-advanced
      - ./crypto-config:/opt/gopath/src/crypto
    networks:
      - delivery-network
