version: '2'

services:

  orderer.delivery-network.com:
    container_name: orderer.delivery-network.com
    image: hyperledger/fabric-orderer:latest
    dns_search: .
    tty: true
    stdin_open: true
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- GODEBUG=netdns=go
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/delivery-network.com/orderers/orderer.delivery-network.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/delivery-network.com/orderers/orderer.delivery-network.com/tls:/var/hyperledger/orderer/tls
    - orderer.delivery-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.customer.delivery-network.com:
    container_name: peer0.customer.delivery-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.customer.delivery-network.com
      - CORE_PEER_ADDRESS=peer0.customer.delivery-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.customer.delivery-network.com:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.customer.delivery-network.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customer.delivery-network.com:7051
      - CORE_PEER_LOCALMSPID=consumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/customer.delivery-network.com/peers/peer0.customer.delivery-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/customer.delivery-network.com/peers/peer0.customer.delivery-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.customer.delivery-network.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.customer.delivery-network.com:
    container_name: peer1.customer.delivery-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.customer.delivery-network.com
      - CORE_PEER_ADDRESS=peer1.customer.delivery-network.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.customer.delivery-network.com:8053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.customer.delivery-network.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.customer.delivery-network.com:7051
      - CORE_PEER_LOCALMSPID=consumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/customer.delivery-network.com/peers/peer1.customer.delivery-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/customer.delivery-network.com/peers/peer1.customer.delivery-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.customer.delivery-network.com:/var/hyperledger/production

    ports:
      - 8051:8051
      - 8053:8053


    container_name: peer1.squad.delivery-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.squad.delivery-network.com
      - CORE_PEER_ADDRESS=peer1.squad.delivery-network.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.squad.delivery-network.com:10053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.squad.delivery-network.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.squad.delivery-network.com:9051
      - CORE_PEER_LOCALMSPID=distributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/squad.delivery-network.com/peers/peer1.squad.delivery-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/squad.delivery-network.com/peers/peer1.squad.delivery-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.squad.delivery-network.com:/var/hyperledger/production
    ports:
      - 10051:10051
      - 10053:10053

  peer0.restaurant.delivery-network.com:
    container_name: peer0.restaurant.delivery-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.restaurant.delivery-network.com
      - CORE_PEER_ADDRESS=peer0.restaurant.delivery-network.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.restaurant.delivery-network.com:11053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.restaurant.delivery-network.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.restaurant.delivery-network.com:12051
      - CORE_PEER_LOCALMSPID=manufacturerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/restaurant.delivery-network.com/peers/peer0.restaurant.delivery-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/restaurant.delivery-network.com/peers/peer0.restaurant.delivery-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.restaurant.delivery-network.com:/var/hyperledger/production
    ports:
      - 11051:11051
      - 11053:11053

  peer1.restaurant.delivery-network.com:
    container_name: peer1.restaurant.delivery-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.restaurant.delivery-network.com
      - CORE_PEER_ADDRESS=peer1.restaurant.delivery-network.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.restaurant.delivery-network.com:12053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.restaurant.delivery-network.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.restaurant.delivery-network.com:11051
      - CORE_PEER_LOCALMSPID=manufacturerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/restaurant.delivery-network.com/peers/peer1.restaurant.delivery-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/restaurant.delivery-network.com/peers/peer1.restaurant.delivery-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.restaurant.delivery-network.com:/var/hyperledger/production
    ports:
      - 12051:12051
      - 12053:12053

  peer0.squad.delivery-network.com:
    container_name: peer0.squad.delivery-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.squad.delivery-network.com
      - CORE_PEER_ADDRESS=peer0.squad.delivery-network.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.squad.delivery-network.com:13053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.squad.delivery-network.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.squad.delivery-network.com:14051
      - CORE_PEER_LOCALMSPID=distributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/squad.delivery-network.com/peers/peer0.squad.delivery-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/squad.delivery-network.com/peers/peer0.squad.delivery-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.squad.delivery-network.com:/var/hyperledger/production
    ports:
      - 13051:13051
      - 13053:13053

  peer1.squad.delivery-network.com:
    container_name: peer1.squad.delivery-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.squad.delivery-network.com
      - CORE_PEER_ADDRESS=peer1.squad.delivery-network.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.squad.delivery-network.com:14053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.squad.delivery-network.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.squad.delivery-network.com:13051
      - CORE_PEER_LOCALMSPID=distributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/squad.delivery-network.com/peers/peer1.squad.delivery-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/squad.delivery-network.com/peers/peer1.squad.delivery-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.squad.delivery-network.com:/var/hyperledger/production
    ports:
      - 14051:14051
      - 14053:14053
